language: php
php:
    - 7.4

script:
    - composer validate
    - vendor/bin/phpcs app/ --standard=vendor/pd/coding-standard/src/PeckaCodingStandard/ruleset.xml
    - vendor/bin/phpcs app/ --standard=vendor/pd/coding-standard/src/PeckaCodingStandardStrict/ruleset.xml
    - vendor/bin/phpstan analyse app/ --level 1 -c phpstan.neon --no-progress

before_script:
    - composer install --no-interaction --prefer-dist

sudo: false

cache:
    directories:
        - $HOME/.composer/cache
